#version 430 core
#extension GL_ARB_compute_shader : require
#extension GL_ARB_shader_storage_buffer_object : require

precision highp float;

layout(local_size_x = 1, local_size_y = 2) in;

layout(std430, binding = 0) volatile buffer position_ssbo
{
	vec4 position[];
};

void calculateMorton()
{

}

// Execute one work group per object. One local invocation per position
void main()
{
	calculateMorton();
}